apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: transactions
  namespace: transactions
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: transactions
  endpoints:
    - port: http
      path: /metrics
      interval: 15s