apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: api-gateway
  labels:
    app: api-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      serviceAccountName: api-gateway-sa
      containers:
        - name: api-gateway
          image: 774493573578.dkr.ecr.us-east-1.amazonaws.com/api-gateway-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8002
          env:
            - name: ACCOUNTS_SERVICE_URL
              value: "http://accounts.accounts.svc.cluster.local"
            - name: TRANSACTIONS_SERVICE_URL
              value: "http://transactions.transactions.svc.cluster.local"
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8002
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8002
            initialDelaySeconds: 5
            periodSeconds: 5